class AdminModel {
  AdminModel({
    required this.vendorId,
    required this.firstname,
    required this.lastname,
    required this.displayName,
    required this.email,
    required this.image,
    required this.telephone,
    required this.salt,
    required this.password,
    required this.fax,
    required this.about,
    required this.company,
    required this.postcode,
    required this.address1,
    required this.address2,
    required this.countryId,
    required this.zoneId,
    required this.city,
    required this.mapUrl,
    required this.facebookUrl,
    required this.googleUrl,
    required this.status,
    required this.productStatus,
    required this.approved,
    required this.languageId,
    required this.paymentMethod,
    required this.paypal,
    required this.bankName,
    required this.bankBranchNumber,
    required this.bankSwiftCode,
    required this.bankAccountName,
    required this.bankAccountNumber,
    required this.storeAbout,
    required this.bankDetail,
    required this.taxNumber,
    required this.shippingCharge,
    required this.logo,
    required this.banner,
    required this.storeLogowidth,
    required this.storeLogoheight,
    required this.storeBannerwidth,
    required this.storeBannerheight,
    required this.commission,
    required this.gst,
    required this.invoicePerfix,
    required this.invoiceContent,
    required this.vdomain,
    required this.dateAdded,
    required this.dateModified,
  });

  String vendorId;
  String firstname;
  String lastname;
  String displayName;
  String email;
  String image;
  String telephone;
  String salt;
  String password;
  String fax;
  String about;
  String company;
  String postcode;
  String address1;
  String address2;
  String countryId;
  String zoneId;
  String city;
  String mapUrl;
  String facebookUrl;
  String googleUrl;
  String status;
  String productStatus;
  String approved;
  String languageId;
  String paymentMethod;
  String paypal;
  String bankName;
  String bankBranchNumber;
  String bankSwiftCode;
  String bankAccountName;
  String bankAccountNumber;
  String storeAbout;
  String bankDetail;
  String taxNumber;
  String shippingCharge;
  String logo;
  String banner;
  String storeLogowidth;
  String storeLogoheight;
  String storeBannerwidth;
  String storeBannerheight;
  String commission;
  String gst;
  String invoicePerfix;
  String invoiceContent;
  String vdomain;
  DateTime dateAdded;
  DateTime dateModified;

  factory AdminModel.fromJson(Map<String, dynamic> json) => AdminModel(
        vendorId: json["vendor_id"],
        firstname: json["firstname"],
        lastname: json["lastname"],
        displayName: json["display_name"],
        email: json["email"],
        image: json["image"],
        telephone: json["telephone"],
        salt: json["salt"],
        password: json["password"],
        fax: json["fax"],
        about: json["about"],
        company: json["company"],
        postcode: json["postcode"],
        address1: json["address_1"],
        address2: json["address_2"],
        countryId: json["country_id"],
        zoneId: json["zone_id"],
        city: json["city"],
        mapUrl: json["map_url"],
        facebookUrl: json["facebook_url"],
        googleUrl: json["google_url"],
        status: json["status"],
        productStatus: json["product_status"],
        approved: json["approved"],
        languageId: json["language_id"],
        paymentMethod: json["payment_method"],
        paypal: json["paypal"],
        bankName: json["bank_name"],
        bankBranchNumber: json["bank_branch_number"],
        bankSwiftCode: json["bank_swift_code"],
        bankAccountName: json["bank_account_name"],
        bankAccountNumber: json["bank_account_number"],
        storeAbout: json["store_about"],
        bankDetail: json["bank_detail"],
        taxNumber: json["tax_number"],
        shippingCharge: json["shipping_charge"],
        logo: json["logo"],
        banner: json["banner"],
        storeLogowidth: json["store_logowidth"],
        storeLogoheight: json["store_logoheight"],
        storeBannerwidth: json["store_bannerwidth"],
        storeBannerheight: json["store_bannerheight"],
        commission: json["commission"],
        gst: json["gst"],
        invoicePerfix: json["invoice_perfix"],
        invoiceContent: json["invoice_content"],
        vdomain: json["vdomain"],
        dateAdded: DateTime.parse(json["date_added"]),
        dateModified: DateTime.parse(json["date_modified"]),
      );

  Map<String, dynamic> toJson() => {
        "vendor_id": vendorId,
        "firstname": firstname,
        "lastname": lastname,
        "display_name": displayName,
        "email": email,
        "image": image,
        "telephone": telephone,
        "salt": salt,
        "password": password,
        "fax": fax,
        "about": about,
        "company": company,
        "postcode": postcode,
        "address_1": address1,
        "address_2": address2,
        "country_id": countryId,
        "zone_id": zoneId,
        "city": city,
        "map_url": mapUrl,
        "facebook_url": facebookUrl,
        "google_url": googleUrl,
        "status": status,
        "product_status": productStatus,
        "approved": approved,
        "language_id": languageId,
        "payment_method": paymentMethod,
        "paypal": paypal,
        "bank_name": bankName,
        "bank_branch_number": bankBranchNumber,
        "bank_swift_code": bankSwiftCode,
        "bank_account_name": bankAccountName,
        "bank_account_number": bankAccountNumber,
        "store_about": storeAbout,
        "bank_detail": bankDetail,
        "tax_number": taxNumber,
        "shipping_charge": shippingCharge,
        "logo": logo,
        "banner": banner,
        "store_logowidth": storeLogowidth,
        "store_logoheight": storeLogoheight,
        "store_bannerwidth": storeBannerwidth,
        "store_bannerheight": storeBannerheight,
        "commission": commission,
        "gst": gst,
        "invoice_perfix": invoicePerfix,
        "invoice_content": invoiceContent,
        "vdomain": vdomain,
        "date_added":
            "${dateAdded.year.toString().padLeft(4, '0')}-${dateAdded.month.toString().padLeft(2, '0')}-${dateAdded.day.toString().padLeft(2, '0')}",
        "date_modified":
            "${dateModified.year.toString().padLeft(4, '0')}-${dateModified.month.toString().padLeft(2, '0')}-${dateModified.day.toString().padLeft(2, '0')}",
      };
}
